id: P000048
initial_creation_type: ebook
created_at: 31/01/2020
last_modified_at: 26/11/2021
source_metadata:
  title: ༄༅། །དྲི་ལན་ལུང་གི་གཏེར་མཛོད་དང་རྒོལ་ལན་ཆབ་ཤོག་བཅས་བཞུགས་སོ། །
  authors:
  - མཛད་པ་པོ། རིག་འཛིན་འཇིགས་མེད་གླིང་པས་མཛད་།
  id: SHE-TAN-017
  layers:
  - book_title
  - author
  - chapter_title
  - quotation
  - sabche
web_metadata:
  title:
    en: Treasury of Scripture:Answers and Official Refutations of Jigme Lingpa
    bo: དྲིས་ལན་ལུང་གི་གཏེར་མཛོད་དང་རྒོལ་ལན་ཆབ་ཤོག་བཅས་བཞུགས་སོ།
  collection:
    en: Shechen Tantra Series–  Book 17
    bo: ''
  author:
    en: Rigzin Jigme Ling
    bo: རིག་འཛིན་འཇིགས་མེད་གླིང།
  pusblisher:
    en: Shechen Publications
    bo: ཞེ་ཆེན་བསྟན་གཉིས་དར་རྒྱས་གླིང།
  sku: SHE-TAN-017
  category:
    en: Uncategorized
    bo: Uncategorized @tib
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: SHE-TAN-017.epub
  description:
    en: ''
    bo: ''
